package com.genfersco.sepbas.domain.model;

public enum TipoEvento {

    INGRESA_JUGADOR,
    SALIDA_JUGADOR,
    LANZAMIENTO_JUGADOR_UN_PUNTO,
    LANZAMIENTO_JUGADOR_DOS_PUNTOS,
    LANZAMIENTO_JUGADOR_TRES_PUNTOS,
    ASISTENCIA_JUGADOR,
    FALTA_JUGADOR;
}
